kumuluzee:
  name: series-stream-parcheese
  env:
    name: dev
  version: 0.0.3
  config:
    etcd:
      hosts: http://159.8.79.87:30024
  discovery:
    etcd:
      hosts: http://159.8.79.87:30024
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: parcheese-endpoint
        url-pattern: /*
  logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="orders">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="806aa11c-d486-41ee-acae-eb0ca61c495a-ls.logit.io" port="22722"
                                                                 protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'